const COLORS = [
  "primary",
  "on-primary",
  "primary-container",
  "on-primary-container",
  "secondary",
  "on-secondary",
  "secondary-container",
  "on-secondary-container",
  "tertiary",
  "on-tertiary",
  "tertiary-container",
  "on-tertiary-container",
  "surface",
  "on-surface",
  "surface-variant",
  "on-surface-variant",
  "surface-container-lowest",
  "surface-container-low",
  "surface-container",
  "surface-container-high",
  "surface-container-highest",
  "success",
  "on-success",
  "success-container",
  "on-success-container",
  "error",
  "on-error",
  "error-container",
  "on-error-container",
  "info",
  "on-info",
  "info-container",
  "on-info-container",
  "warning",
  "on-warning",
  "warning-container",
  "on-warning-container",
];

const FORMATS = [
  { label: "CSS", value: "css" },
  { label: "SCSS", value: "scss" },
  { label: "JSON", value: "json" },
  { label: "Tailwind", value: "tailwind" },
  { label: "Dynamic", value: "dynamic" },
];

export { COLORS, FORMATS };
